In [3]:
import torch

## Tensors
Building blocks of ML

### Creating tensors

In [4]:
# A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# As it is a single number,it has no item
scalar.ndim

0

In [6]:
# This only works in case of scalars.
scalar.item()

7

In [22]:
# Vectors
vector = torch.tensor([1,2])

print(vector.ndim)

# Returns the shape => 1 x 2 matrix => vector
print(vector.shape)
print(vector.size())

1
torch.Size([2])
torch.Size([2])


In [27]:
# Matrices
M = torch.tensor([
    [1,2],
    [2,3],
    [3,4]
])
print(M.ndim)
print(M.shape)
print(M.size())

tensor([[1, 2],
        [2, 3],
        [3, 4]])
2
torch.Size([3, 2])
torch.Size([3, 2])


In [31]:
# Tensor
T = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [0,1,2],
        [3,4,5],
        [6,7,8]
    ]
])

# We've got two 3 x 3 matrices
T.shape

torch.Size([2, 3, 3])

### Random Tensors

In [43]:
# Create a random tensor by giving it a shape/size 

# generates a random 2 x 2 matrix
random_tensor = torch.rand(2,2)
random_tensor

tensor([[0.9314, 0.3621],
        [0.8701, 0.2376]])

In [44]:
random_tensor.ndim

2

### 0's and 1's

In [54]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])