In [2]:
import torch

## Tensors
Building blocks of ML

### Creating tensors

#### vectors,matrices,tensors

In [4]:
# A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# As it is a single number,it has no item
scalar.ndim

0

In [6]:
# This only works in case of scalars.
scalar.item()

7

In [22]:
# Vectors
vector = torch.tensor([1,2])

print(vector.ndim)

# Returns the shape => 1 x 2 matrix => vector
print(vector.shape)
print(vector.size())

1
torch.Size([2])
torch.Size([2])


In [27]:
# Matrices
M = torch.tensor([
    [1,2],
    [2,3],
    [3,4]
])
print(M.ndim)
print(M.shape)
print(M.size())

tensor([[1, 2],
        [2, 3],
        [3, 4]])
2
torch.Size([3, 2])
torch.Size([3, 2])


In [31]:
# Tensor
T = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [0,1,2],
        [3,4,5],
        [6,7,8]
    ]
])

# We've got two 3 x 3 matrices
T.shape

torch.Size([2, 3, 3])

#### Random Tensors

In [43]:
# Create a random tensor by giving it a shape/size 

# generates a random 2 x 2 matrix
random_tensor = torch.rand(2,2)
random_tensor

tensor([[0.9314, 0.3621],
        [0.8701, 0.2376]])

In [44]:
random_tensor.ndim

2

#### 0's and 1's

In [54]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

#### Range tensors

In [20]:
# can generate only 1-D tensors
range = torch.arange(1,5)
range

tensor([1, 2, 3, 4])

#### Tensor Datatypes

https://pytorch.org/docs/stable/tensors.html

In [18]:
f_16 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float16)
f_32 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
i_32 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int32)
i_64 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int64)

#### Manipulating Tensors
Add, Sub, Mult, Div, Matrix mult, transpose

In [26]:
tens = torch.tensor([1,2,3])
tens*10,tens+10,tens-10,tens/10

(tensor([10, 20, 30]),
 tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]))

In [42]:
# Matrix multiplication (OUTER DIMENSION(COL) MUST MATCH)
t1 = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])
t2 = torch.tensor([
    [1,2],
    [3,4]
])
torch.matmul(t1,t2)

tensor([[ 7, 10],
        [15, 22],
        [23, 34]])

In [43]:
#transpose
t1.T

tensor([[1, 3, 5],
        [2, 4, 6]])

#### Tensor aggregates
Mean, Max, Min, Sum

In [75]:
t = torch.arange(0,10,dtype=torch.float64)
# .mean() will ONLY work on float & complex datatype tensor, arange() returns LONG tensor
t.mean(),t.min(),t.max(),t.sum()

(tensor(4.5000, dtype=torch.float64),
 tensor(0., dtype=torch.float64),
 tensor(9., dtype=torch.float64),
 tensor(45., dtype=torch.float64))

In [76]:
# Index of max and min element
t.argmax(),t.argmin()

(tensor(9), tensor(0))