In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [5]:
voc_size = 10000

In [7]:
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[9316, 5276, 5610, 9900],
 [9316, 5276, 5610, 7507],
 [9316, 5042, 5610, 206],
 [5513, 7504, 6499, 9210, 6561],
 [5513, 7504, 6499, 9210, 6561],
 [5513, 7504, 6499, 9210, 1089],
 [4771, 9316, 1643, 5610, 7905],
 [410, 2477, 2548, 9210]]

## Word Embedding Representation

In [9]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
sent_length=8
'''
The size of the inputs must be same when training a DL model, so when you have inputs of different shapes,you have
to add padding(0s) either to the front (post) or to the back (pre) to make the shapes equal.
'''
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)

In [12]:
embedded_docs

array([[   0,    0,    0,    0, 9316, 5276, 5610, 9900],
       [   0,    0,    0,    0, 9316, 5276, 5610, 7507],
       [   0,    0,    0,    0, 9316, 5042, 5610,  206],
       [   0,    0,    0, 5513, 7504, 6499, 9210, 6561],
       [   0,    0,    0, 5513, 7504, 6499, 9210, 6561],
       [   0,    0,    0, 5513, 7504, 6499, 9210, 1089],
       [   0,    0,    0, 4771, 9316, 1643, 5610, 7905],
       [   0,    0,    0,    0,  410, 2477, 2548, 9210]])

In [13]:
dim=10

In [23]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\ML\SIMPLE_RNN\rnn_venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 901ms/step


array([[[ 2.01815479e-02, -1.33834258e-02,  3.62834595e-02,
          2.31250040e-02,  4.68109958e-02,  1.84924714e-02,
         -4.65243831e-02, -2.73333434e-02, -1.00710392e-02,
         -3.72816809e-02],
        [ 2.01815479e-02, -1.33834258e-02,  3.62834595e-02,
          2.31250040e-02,  4.68109958e-02,  1.84924714e-02,
         -4.65243831e-02, -2.73333434e-02, -1.00710392e-02,
         -3.72816809e-02],
        [ 2.01815479e-02, -1.33834258e-02,  3.62834595e-02,
          2.31250040e-02,  4.68109958e-02,  1.84924714e-02,
         -4.65243831e-02, -2.73333434e-02, -1.00710392e-02,
         -3.72816809e-02],
        [ 2.01815479e-02, -1.33834258e-02,  3.62834595e-02,
          2.31250040e-02,  4.68109958e-02,  1.84924714e-02,
         -4.65243831e-02, -2.73333434e-02, -1.00710392e-02,
         -3.72816809e-02],
        [-4.28466573e-02, -4.21372652e-02, -1.03796646e-03,
          2.90609710e-02,  2.76086070e-02, -7.33383745e-03,
         -3.53873484e-02,  9.92808491e-03,  1.981161

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 9316, 5276, 5610, 9900])

In [29]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[ 0.02018155, -0.01338343,  0.03628346,  0.023125  ,  0.046811  ,
         0.01849247, -0.04652438, -0.02733334, -0.01007104, -0.03728168],
       [ 0.02018155, -0.01338343,  0.03628346,  0.023125  ,  0.046811  ,
         0.01849247, -0.04652438, -0.02733334, -0.01007104, -0.03728168],
       [ 0.02018155, -0.01338343,  0.03628346,  0.023125  ,  0.046811  ,
         0.01849247, -0.04652438, -0.02733334, -0.01007104, -0.03728168],
       [ 0.02018155, -0.01338343,  0.03628346,  0.023125  ,  0.046811  ,
         0.01849247, -0.04652438, -0.02733334, -0.01007104, -0.03728168],
       [-0.04284666, -0.04213727, -0.00103797,  0.02906097,  0.02760861,
        -0.00733384, -0.03538735,  0.00992808,  0.01981162, -0.01545103],
       [ 0.0178243 ,  0.03587617,  0.03408268, -0.00072526, -0.00865139,
        -0.01004475,  0.04956971,  0.01526536, -0.01885122, -0.04472196],
       [ 0.03314617, -0.04326406,  0.02368944, -0.02769178,  0.01702799,
         0.00419502, -0.00988922, -0.04320071