# Data Preprocessing Tools

Data Processing is the process of converting raw data to suitable format for training and building ML models.

The processes involved are:
  1. Data Cleaning (Handle Missing Values)
  2. Data Transformation (Feauture Scaling - Normalization,Standardization)
  3. Data Splitting (Splitting data into training and test models)

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('Data.csv')
# 1. Separating the feautures and dependent variables

# 2. Here X contains the data frame for the first 3 columns of the dataset
X = dataset.iloc[:,:-1].values

# 3. Here Y contains the data frame for the last column of the dataset
Y = dataset.iloc[:,-1].values

In [4]:
# Sum of the total number of entries that are null in each column
print(dataset.isnull().sum())

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [5]:
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [6]:
# Two ways to handle missing data
# 1. Delete the row that has missing data
# 2. Replace the missing cell with the average/median/frequent of the values of a particular column

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")

# will look for all the missing cells(make sure to select ONLY numerical columns)
# you can also pass the dataset as it is as a arguement
imputer.fit(X[:,1:3])

# returns the updated data frame
# you can also pass the dataset as it is as a arguement
X[:,1:3] = imputer.transform(X[:,1:3])

In [7]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

If there is a datatype other than numbers in the dataset, the ML model will have a hard time analysing it.So what we can do is we can group similar values in a column(that are not numbers) into a category(Encoding Categorical).

### Encoding the Independent Variable

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# specify what kind of transformations we will do, and on which indice(s) we will do so

# ColumnTransformer's transformers takes 3 params: operation name,type of operation,column index(s) you want to transform
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],
                       # passthrough = keep the columns that are not being transformed as it is
                       remainder='passthrough')

# X(feautures) is expected to be a numpy array
X = np.array(ct.fit_transform(X))


In [9]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# Y(dependent variables) are not expected to be numpy arrays
Y = le.fit_transform(Y)

In [11]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set