# Data Preprocessing Tools

Data Processing is the process of converting raw data to suitable format for training and building ML models.

The processes involved are:
  1. Data Cleaning (Handle Missing Values)
  2. Data Transformation (Feauture Scaling - Normalization,Standardization)
  3. Data Splitting (Splitting data into training and test models)

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
# While reading the CSV, check the delimiter used, if its anything other than a comma, you have to specify a delimiter parameter.
dataset = pd.read_csv('Data.csv')
# 1. Separating the feautures(X) and dependent variables(Y)

# 2. Here X contains the data frame for the first 3 columns of the dataset
X = dataset.iloc[:,:-1].values

# 3. Here Y contains the data frame for the last column of the dataset
Y = dataset.iloc[:,-1].values

In [ ]:
# Sum of the total number of entries that are null in each column
print(dataset.isnull().sum())

In [4]:
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
# Two ways to handle missing data
# 1. Delete the row that has missing data
# 2. Replace the missing cell with the average/median/frequent of the values of a particular column

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")

# will look for all the missing cells(make sure to select ONLY numerical columns)
# you can also pass the dataset to it is as an arguement
imputer.fit(X[:,1:3])

# returns the updated data frame
# you can also pass the dataset as it is as an arguement
X[:,1:3] = imputer.transform(X[:,1:3])

In [ ]:
print(X)

## Encoding categorical data

If there is a datatype other than numbers in the dataset, the ML model will have a hard time analysing it.So what we can do is we can group similar values in a column(that are not numbers) into a category(Encoding Categorical).

### Encoding the Independent Variable

In [7]:
# One Hot Encoding is used when there is no kind of relationship between the values in a column
# Eg. Lets say we have a column Fruits, with values apple,bannana, & kiwi, there is no relationship between between these values
# NOTE: Doing so, the dimensions of the table WILL increase

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# specify what kind of transformations we will do, and on which indice(s) we will do so

# ColumnTransformer's transformers takes 3 params: operation name,type of operation,column index(s) you want to transform
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],
                       # passthrough = keep the columns that are not being transformed as it is
                       remainder='passthrough')

# X(feautures) is expected to be a numpy array
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


print(X)

In [ ]:
# If the encoding is done directly from the dataset(i.e without separating it into dependent variables and feautures)

# ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[pass the column name(s) here])],remainder='passthrough')
# le = LabelEncoder()
# le.fit_tansform(dataset[columnName])

### Encoding the Dependent Variable

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

Y = le.fit_transform(Y)

## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes']
['No' 'Yes']


## Feauture Scaling
This is done in order to avoid feautures/columns being dominated by other feautures/columns in such a way that the dominated feautures will not even be considered in ML model

Standardisation = X - mean(X)/ Standard Deviation(X) [-3,+3]


In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Feauture Scaling must NOT be applied to all feautures/columns i.e it is not necessary to apply it to features that were encoded because it already lies between 0 and 1.

# fit - calculates the mean and standard deviation of the values in the column
# transform - obvious innit
X_train[:,3:] = scaler.fit_transform(X_train[:,3:])

#transform method on the test data is to ensure that the test data is processed in the same way as the training data
X_test[:,3:] = scaler.transform(X_test[:,3:])

print(X_train)
# print(X_test)

[[1.0 0.0 0.0 1.2909944487358056 -0.19159184384578554 -1.0781259408412427]
 [1.0 0.0 1.0 -0.7745966692414833 -0.014117293757057846
  -0.07013167641635404]
 [0.0 1.0 0.0 -0.7745966692414833 0.5667085065333239 0.6335624327104546]
 [1.0 0.0 0.0 1.2909944487358056 -0.3045301939022487 -0.307866172742979]
 [1.0 0.0 0.0 1.2909944487358056 -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 -0.7745966692414833 1.1475343068237056 1.2326533634535488]
 [1.0 0.0 1.0 -0.7745966692414833 1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 -0.7745966692414833 -0.7401495441200352 -0.5646194287757336]]
